# Generated by Django 4.2.5 on 2023-09-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('siren', models.BigAutoField(primary_key=True, serialize=False)),
                ('denomination', models.CharField(max_length=200)),
                ('numtva', models.CharField(max_length=13)),
                ('activite_principale', models.CharField(max_length=100)),
                ('naf', models.CharField(max_length=5)),
                ('adresse', models.CharField(max_length=200)),
                ('nature_juridique', models.CharField(max_length=200)),
                ('effectif_salarie', models.IntegerField()),
                ('date_naissance', models.DateTimeField(verbose_name='date de création')),
                ('convention', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('date_naissance', models.DateTimeField(verbose_name='date de naissance')),
                ('adresse', models.CharField(max_length=200)),
                ('numtel', models.IntegerField()),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('numlicence', models.IntegerField()),
                ('horaires', models.CharField(max_length=200)),
                ('agenda', models.URLField()),
                ('photo', models.CharField(max_length=200)),
                ('accept_mutuel', models.BooleanField()),
                ('specialite', models.CharField(max_length=50)),
                ('etablissement', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='home.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('num_secu', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('date_naissance', models.DateTimeField(verbose_name='date de naissance')),
                ('adresse', models.CharField(max_length=200)),
                ('numtel', models.IntegerField()),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('pathologie', models.CharField(max_length=200)),
                ('mutuelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
    ]
