# Generated by Django 4.2.5 on 2023-11-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user__adresse_mail_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
