# Generated by Django 4.2.5 on 2023-11-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user__date_naissance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_adresse',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_date_naissance',
            new_name='date_naissance',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_num_tel',
            new_name='num_tel',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_sexe_f',
            new_name='sexe_f',
        ),
    ]
