# Generated by Django 4.2.5 on 2023-11-27 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('path', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='EnregistrementFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('niveau', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_td', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('BTS', 'BTS'), ('DUT', 'DUT'), ('CPGE', 'CPGE'), ('Formation professionnelle', 'Formation professionnelle'), ('Autre', 'Autre')], max_length=255)),
                ('duree_mois', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupeEtude',
            fields=[
                ('id_group', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_groupe', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('duree', models.TimeField()),
                ('autres_informations', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatiereFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('contenu', models.CharField(blank=True, max_length=255, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='MembresGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('role_groupe', models.CharField(choices=[('admin', 'Administrateur'), ('lecteur', 'Lecteur'), ('user', 'User')], max_length=255)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.groupeetude')),
            ],
        ),
    ]
