# Generated by Django 4.2.5 on 2023-11-28 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participationforum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membresgroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.groupeetude'),
        ),
        migrations.AddField(
            model_name='membresgroupe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matiereformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.formation'),
        ),
        migrations.AddField(
            model_name='matiereformation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.matiere'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groupeetude'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formation',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.matiere'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enregistrementformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.formation'),
        ),
        migrations.AddField(
            model_name='enregistrementformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
