name: Automatiser les tags et les badges

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier la version
      run: |
        # Récupérez la version du logiciel à partir de votre code ou d'un fichier
        software_version=$(cat version.txt)

        # Créez un tag basé sur la version
        git tag -a v${software_version} -m "Version ${software_version}"

        # Poussez le tag vers le référentiel
        git push origin v${software_version}

    - name: Créer un badge
      run: |
        # Créez un badge Markdown avec le tag
        badge="[![Version](https://img.shields.io/badge/version-${software_version}-blue.svg)](https://github.com/Jessi91/Rstudy/releases/tag/v${software_version})"
        
        # Ajoutez le badge au fichier README.md (ou tout autre fichier de votre choix)
        echo $badge >> README.md

    - name: Valider les modifications et les pousser vers le référentiel
      run: git commit -am "Ajout du badge de version" && git push
