version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  mysql:
    image: mysql:latest
    container_name: some-mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "3306"

volumes:
  data:
